import Head from 'next/head';
import Header from '@/Components/Header';
import Introduction from '@/Components/Introduction';

export default function Home() {
    return (
        <>
            <Head>
                <title>Astra NFT Marketplace</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/img3.png' />
            </Head>
            <Header />
            <Introduction />
        </>
    );
}
